- name: print local
  hosts: all
  gather_facts: true
  tasks:
    - block:
        - debug:
            var: ansible_play_hosts_all
        - debug:
            var: ansible_play_hosts
        - set_fact:
            down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
        - debug:
            var: down
      run_once: true 

    - name: run the script on the node
      script: script.sh
      register: script  
      when: ansible_facts['distribution'] == 'RedHat'       
      ignore_errors: true


    - template: 
          src: template.j2
          dest: ./out
      delegate_to: localhost
      ignore_errors: true
